### PR TITLE
Please don't squash merges

### PR DESCRIPTION
**Pull request by bburky**
Is there any reason you haven't been using normal git merges from the stable linux git tree for version updates? It makes it far harder to compare your changes to the mainline linux tree. Also you have made unrelated changes a couple times while updating versions.

If you are concerned it will make the git history hard to read, you can run git-log like this to show the merges as only one item: `git log --oneline --first-parent v4.14..`

The branch in this pull request is a recreation of your main branch but using merges for each of the v4.14.xx updates. If you want this version, you can't really merge this pull request normally, instead you could switch your main branch to point to it with a hard git reset. That will mess up your current branches a little though, they will no longer share history with your main branch, you will have to cherry-pick them into main instead of merging them.

The only difference in my branch is that it includes arch/x86/boot/compressed/pgtable_64.c which you accidentally lost during the v4.14.8 update.

### CODE REVIEW

**Comment by frank-w** [comment]
The linux mainline (which i forked from) does not have the 14.4.xx tags so i used the incremental patches from kernel.org. which unrelated changes do you mean (build.sh)?

I'm a beginner in git,but i do my best

**Comment by bburky** [comment]
You can find tags for all the v4.14.xx versions in the linux-stable repository: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git

Run the following commands in git:
```
git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
git fetch stable
```

And then you will have tags for all the point releases. You can just run `git merge v4.14.1234` in the future.

**Comment by bburky** [comment]
I was referring to commits like https://github.com/frank-w/BPI-R2-4.14/commit/c0939efabfe08c79c780aada16aca3e1812cfe1a. You updated to 4.14.11 and also added other changes. This makes it more difficult for others to figure out what changes you have made vs what changes are the update.

Thanks for all your work on this kernel though! It's nice to have a kernel available that's very close to mainline for the BPI-R2.

**Comment by frank-w** [comment]
I respect your work for reorganising my main tree. I worry about the history of the branches when i merge...is the full history gone or only the history which is same with branch (before branch was created)?

**Comment by bburky** [comment]
You won't lose anything. The branches would still be there. What I did was recreate each commit of yours from v4.14 onwards, adding merges from linux-stable where appropriate. But the commits have different hashes, so merges don't quite work.

The problem with history is that your existing branches are branched off from your code, not my new branch. So running `git merge one-of-your-current-branches` won't do what you want. Instead you can `git cherry-pick` each of the commits from your branches when you want to merge them back in.

If you'd like to look at the branch I made you can follow these steps: https://help.github.com/articles/checking-out-pull-requests-locally/

The following steps are probably enough:
```
git fetch origin pull/13/head:unsquashed-merges
git checkout unsquashed-merges
```

That won't mess up your `main` branch unless you do anything to change it.

You can ignore all of this if you want though. That's okay.

**Comment by frank-w** [comment]
added the pull-request to branch main_unsquashed, right so far?

now i need to add the add the additional remote-repo for the tags?

at last step i rename main to any main_old and the main_unsquashed to squashed...and check if new main is the default branch

**Comment by bburky** [comment]
It looks good now. I hope you found this useful and it made the 4.14.17 update easier.

**Comment by bburky** [comment]
In the future you will need to redo the fetch to download the new tags for new versions. And then the merge to actually do the update, and push it back to github.

**Comment by frank-w** [comment]
can i create a branch from my main (e.g. main_4.15) and upgrade to 4.15? tried to make a merge, but that failes

**Comment by bburky** [comment]
The problem is that the mainline v4.15 tag is not ahead of the v4.14.xx tags in the linux-stable repository, they have diverging histories. You would have had similar problems in your old repository too (before I added merges).

Instead you want to copy all your commits (but not the code merged from linux-stable) from main to the other branch. Normally you would do this with git rebase like this:

```
git checkout main -b main-v4.15
git rebase v4.15
```

But that doesn't work because you don't want your v4.14.xx merges to be included in the rebase.

Instead you can use this somewhat complicated cherry-pick:

```
# Create a new branch called main-4.15 from the at v4.15 from mainline
git checkout v4.15 -b  main-4.15
# Copy all the bpi-r2 commits (not from merges) into the v4.15 branch
git cherry-pick --first-parent --no-merges v4.14..main
```

It looks like you will have a merge conflict when that applies ae21f4e680cf "apply mmc- and pcie-patch", and multiple changes to .gitignore. You will need to resolve and commit merge confilcts like usual, and then run `git cherry-pick --continue` each time.

This is actually very simple if you never merge though. You can just run `git rebase v4.16` next time instead of cherry-pick.

Merge and rebase both have similar results but work very differently. There are different drawbacks to each. I didn't mean to make every thing complicated, sorry! You are trying to slightly complicated things in git though.

**Comment by bburky** [comment]
You could modify main to not have any merges.

```
git checkout v4.14.18 -b main-no-merges
git cherry-pick --first-parent --no-merges v4.14..main
```

That would create a new main-no-merges branch which has no merges. You could then easily rebase to update to new versions (instead of merging). You could run `git rebase v4.14.19` to update to the next stable release. Or create a 4.15 branch by making a new branch then running `git rebase -i --onto v4.15 v4.14.18`

You often have a choice of using merge or rebase, and things get complicated if you use both. Normally people don't like rebase because it changes history. It also can make it difficult for other people to work from the code, they will get errors when they run `git pull`. That doesn't matter too much for your v4.14.xx to v4.15 situation though.

(I feel like I'm not explaining any of this well, sorry.)

**Pull request closed without merging**
